// regexes
const kebabCase = '^([a-z][a-z0-9]*)(-[a-z0-9]+)*$';
const screamingSnakeCase = '^([A-Z][A-Z0-9]*)(_[A-Z0-9]+)*$';
const prefixes = '^(t|p|s|c|l|u|has|is)-';
const block = '([a-z]+-?[a-z]*)';
const element = '(__[a-z]+-?[a-z]*)?';
const modifier = '(--[a-z]+-?[a-z]*)?$';
const vendor = '^v-.+$';
const bem = `${block}${element}${modifier}`;
const selectorBemLike = `${prefixes}${bem}|${vendor}`;
const variableBemLike = `^${bem}|${screamingSnakeCase}`;

module.exports = {
  // add your custom config here
  // https://stylelint.io/user-guide/configuration
  extends: ['stylelint-config-recess-order'],
  plugins: ['stylelint-scss'],
  rules: {
    /**
     * Possible errors
     */
    'color-no-invalid-hex': true,
    'font-family-no-duplicate-names': true,
    'font-family-no-missing-generic-family-keyword': true,
    'named-grid-areas-no-invalid': true,
    'function-calc-no-invalid': true,
    'function-calc-no-unspaced-operator': true,
    'function-linear-gradient-no-nonstandard-direction': true,
    'string-no-newline': true,
    'unit-no-unknown': true,
    'property-no-unknown': true,
    'keyframe-declaration-no-important': true,
    'declaration-block-no-duplicate-custom-properties': true,
    'declaration-block-no-duplicate-properties': true,
    'declaration-block-no-shorthand-property-overrides': true,
    'block-no-empty': true,
    'selector-pseudo-class-no-unknown': true,
    'selector-pseudo-element-no-unknown': true,
    'selector-type-no-unknown': true,
    'media-feature-name-no-unknown': true,
    'at-rule-no-unknown': null, // delegate to stylelint-scss
    'comment-no-empty': null, // delegate to stylelint-scss
    'no-descending-specificity': true,
    'no-duplicate-at-import-rules': true,
    'no-duplicate-selectors': true,
    'no-empty-source': null,
    'no-extra-semicolons': true,
    'no-invalid-double-slash-comments': true,

    /**
     * Limit language features
     */
    'alpha-value-notation': 'number',
    'hue-degree-notation': 'number',
    'color-function-notation': 'legacy',
    'color-named': 'never',
    'color-no-hex': true,
    'length-zero-no-unit': true,
    'font-weight-notation': 'numeric',
    'function-allowed-list': null,
    'function-disallowed-list': ['darken', 'lighten'],
    'function-url-no-scheme-relative': true,
    'function-url-scheme-allowed-list': null,
    'function-url-scheme-disallowed-list': ['ftp', 'http'],
    'keyframes-name-pattern': new RegExp(kebabCase),
    'number-max-precision': 10,
    'time-min-milliseconds': [100, { ignore: ['delay'] }],
    'unit-allowed-list': null,
    'unit-disallowed-list': ['ms'],
    'shorthand-property-no-redundant-values': true,
    'value-no-vendor-prefix': true,
    'custom-property-pattern': new RegExp(variableBemLike),
    'property-allowed-list': null,
    'property-disallowed-list': null,
    'property-no-vendor-prefix': true,
    'declaration-block-no-redundant-longhand-properties': [
      true,
      {
        ignoreShorthands: ['grid-template'],
      },
    ],
    'declaration-no-important': true,
    'declaration-property-unit-allowed-list': null,
    'declaration-property-unit-disallowed-list': null,
    'declaration-property-value-allowed-list': {
      // CSS-generated content is not included in the DOM
      content: ["''", "'attr(aria-label)'"],
    },
    'declaration-property-value-disallowed-list': {
      // use "border: 0" instead
      border: ['none'],
      'border-top': ['none'],
      'border-right': ['none'],
      'border-bottom': ['none'],
      'border-left': ['none'],

      // improve accessibility
      display: ['none'],
      outline: ['0', 'none'],
      'text-align': ['justify'],
    },
    'declaration-block-single-line-max-declarations': 1,
    'selector-attribute-name-disallowed-list': ['disabled', 'id'],
    'selector-attribute-operator-allowed-list': null,
    'selector-attribute-operator-disallowed-list': null,
    'selector-class-pattern': new RegExp(selectorBemLike),
    'selector-combinator-allowed-list': null,
    'selector-combinator-disallowed-list': null,
    'selector-id-pattern': null,
    'selector-max-attribute': 1,
    'selector-max-class': 2,
    'selector-max-combinators': 2,
    'selector-max-compound-selectors': 3,
    'selector-max-empty-lines': 0,
    'selector-max-id': 0,
    'selector-max-pseudo-class': 2,
    'selector-max-specificity': null,
    'selector-max-type': 2,
    'selector-max-universal': 2,
    'selector-nested-pattern': null,
    'selector-no-qualifying-type': true,
    'selector-no-vendor-prefix': true,
    'selector-pseudo-class-allowed-list': null,
    'selector-pseudo-class-disallowed-list': null,
    'selector-pseudo-element-allowed-list': null,
    'selector-pseudo-element-colon-notation': 'double',
    'selector-pseudo-element-disallowed-list': null,
    'media-feature-name-allowed-list': null,
    'media-feature-name-disallowed-list': null,
    'media-feature-name-no-vendor-prefix': true,
    'media-feature-name-value-allowed-list': null,
    'custom-media-pattern': new RegExp(kebabCase),
    'at-rule-allowed-list': null,
    'at-rule-disallowed-list': ['debug'],
    'at-rule-no-vendor-prefix': true,
    'at-rule-property-required-list': null,
    'comment-pattern': null,
    'comment-word-disallowed-list': null,
    'max-nesting-depth': [
      1,
      {
        ignore: ['pseudo-classes'],
        ignoreAtRules: [
          'each',
          'include',
          'media',
          'supports',
        ],
      },
    ],
    'no-unknown-animations': true,

    /**
     * Stylistic issues
     */
    'color-hex-case': 'lower',
    'color-hex-length': 'long',
    'font-family-name-quotes': 'always-unless-keyword',
    'function-comma-newline-after': 'always-multi-line',
    'function-comma-newline-before': null,
    'function-comma-space-after': 'always-single-line',
    'function-comma-space-before': 'never',
    'function-max-empty-lines': 0,
    'function-name-case': 'lower',
    'function-parentheses-newline-inside': 'always-multi-line',
    'function-parentheses-space-inside': 'never-single-line',
    'function-url-quotes': 'always',
    'function-whitespace-after': 'always',
    'number-leading-zero': 'always',
    'number-no-trailing-zeros': true,
    'string-quotes': 'single',
    'unit-case': 'lower',
    'value-keyword-case': 'lower',
    'value-list-comma-newline-after': 'always-multi-line',
    'value-list-comma-newline-before': null,
    'value-list-comma-space-after': 'always-single-line',
    'value-list-comma-space-before': 'never',
    'value-list-max-empty-lines': 0,
    'custom-property-empty-line-before': [
      'always',
      {
        except: ['after-comment', 'after-custom-property', 'first-nested'],
        ignore: ['inside-single-line-block'],
      },
    ],
    'property-case': 'lower',
    'declaration-bang-space-after': 'never',
    'declaration-bang-space-before': 'always',
    'declaration-colon-newline-after': 'always-multi-line',
    'declaration-colon-space-after': 'always-single-line',
    'declaration-colon-space-before': 'never',
    'declaration-empty-line-before': [
      'always',
      {
        except: ['after-comment', 'after-declaration', 'first-nested'],
        ignore: ['inside-single-line-block'],
      },
    ],
    'declaration-block-semicolon-newline-after': 'always-multi-line',
    'declaration-block-semicolon-newline-before': null,
    'declaration-block-semicolon-space-after': 'always-single-line',
    'declaration-block-semicolon-space-before': 'never',
    'declaration-block-trailing-semicolon': 'always',
    'block-closing-brace-empty-line-before': 'never',
    'block-closing-brace-newline-after': 'always',
    'block-closing-brace-newline-before': 'always-multi-line',
    'block-closing-brace-space-after': null,
    'block-closing-brace-space-before': 'always-single-line',
    'block-opening-brace-newline-after': 'always-multi-line',
    'block-opening-brace-newline-before': null,
    'block-opening-brace-space-after': 'always-single-line',
    'block-opening-brace-space-before': 'always',
    'selector-attribute-brackets-space-inside': 'never',
    'selector-attribute-operator-space-after': 'never',
    'selector-attribute-operator-space-before': 'never',
    'selector-attribute-quotes': 'always',
    'selector-combinator-space-after': 'always',
    'selector-combinator-space-before': 'always',
    'selector-descendant-combinator-no-non-space': true,
    'selector-pseudo-class-case': 'lower',
    'selector-pseudo-class-parentheses-space-inside': 'never',
    'selector-pseudo-element-case': 'lower',
    'selector-type-case': 'lower',
    'selector-list-comma-newline-after': 'always',
    'selector-list-comma-newline-before': null,
    'selector-list-comma-space-after': null,
    'selector-list-comma-space-before': 'never',
    'rule-empty-line-before': [
      'always-multi-line',
      {
        except: ['first-nested'],
        ignore: ['after-comment'],
      },
    ],
    'media-feature-colon-space-after': 'always',
    'media-feature-colon-space-before': 'never',
    'media-feature-name-case': 'lower',
    'media-feature-parentheses-space-inside': 'never',
    'media-feature-range-operator-space-after': 'always',
    'media-feature-range-operator-space-before': 'always',
    'media-query-list-comma-newline-after': 'always-multi-line',
    'media-query-list-comma-newline-before': null,
    'media-query-list-comma-space-after': 'always-single-line',
    'media-query-list-comma-space-before': 'never',
    'at-rule-empty-line-before': [
      'always',
      {
        except: ['blockless-after-same-name-blockless', 'first-nested'],
        ignore: ['after-comment'],
        ignoreAtRules: ['else'],
      },
    ],
    'at-rule-name-case': 'lower',
    'at-rule-name-newline-after': null,
    'at-rule-name-space-after': 'always-single-line',
    'at-rule-semicolon-newline-after': 'always',
    'at-rule-semicolon-space-before': 'never',
    'comment-empty-line-before': [
      'always',
      {
        except: ['first-nested'],
        ignore: ['after-comment', 'stylelint-commands'],
      },
    ],
    'comment-whitespace-inside': 'always',
    indentation: [2, { baseIndentLevel: 1 }],
    linebreaks: 'unix',
    'max-empty-lines': 1,
    'max-line-length': 80,
    'no-eol-whitespace': true,
    'no-missing-end-of-source-newline': true,
    'no-empty-first-line': true,
    'unicode-bom': 'never',

    /**
     * SCSS
     */
    'scss/at-each-key-value-single-line': true,
    'scss/at-extend-no-missing-placeholder': true,
    'scss/at-function-parentheses-space-before': 'never',
    'scss/at-function-pattern': new RegExp(kebabCase),
    'scss/at-if-no-null': true,
    'scss/at-import-no-partial-leading-underscore': true,
    'scss/at-import-partial-extension': 'never',
    'scss/at-mixin-argumentless-call-parentheses': 'always',
    'scss/at-mixin-parentheses-space-before': 'never',
    'scss/at-mixin-pattern': new RegExp(kebabCase),
    'scss/at-rule-no-unknown': true,
    'scss/comment-no-empty': true,
    'scss/declaration-nested-properties': 'never',
    'scss/dimension-no-non-numeric-values': true,
    'scss/dollar-variable-colon-space-after': 'always',
    'scss/dollar-variable-colon-space-before': 'never',
    'scss/dollar-variable-empty-line-after': [
      'always',
      {
        except: ['before-dollar-variable', 'last-nested'],
        ignore: ['inside-single-line-block'],
      },
    ],
    'scss/dollar-variable-empty-line-before': [
      'always',
      {
        except: ['after-comment', 'after-dollar-variable', 'first-nested'],
        ignore: ['inside-single-line-block'],
      },
    ],
    'scss/dollar-variable-first-in-block': [
      true,
      {
        except: ['root'],
      },
    ],
    'scss/dollar-variable-no-missing-interpolation': true,
    'scss/dollar-variable-pattern': new RegExp(variableBemLike),
    'scss/double-slash-comment-empty-line-before': [
      'always',
      {
        except: ['first-nested'],
        ignore: ['between-comments', 'stylelint-commands'],
      },
    ],
    'scss/double-slash-comment-whitespace-inside': 'always',
    'scss/function-color-relative': true,
    'scss/function-quote-no-quoted-strings-inside': true,
    'scss/function-unquote-no-unquoted-strings-inside': true,
    'scss/map-keys-quotes': 'always',
    'scss/media-feature-value-dollar-variable': [
      'always',
      {
        ignore: ['keywords'],
      },
    ],
    'scss/no-duplicate-dollar-variables': true,
    'scss/no-duplicate-mixins': true,
    'scss/operator-no-newline-after': true,
    'scss/operator-no-newline-before': true,
    'scss/operator-no-unspaced': true,
    'scss/percent-placeholder-pattern': new RegExp(bem),
    'scss/selector-nest-combinators': null,
    'scss/selector-no-redundant-nesting-selector': true,
    'scss/selector-no-union-class-name': true,
  },
};
